version: 2
jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Bonjour j'écoute Clara Luciani"
      - run: sleep 15
  workflows:
    version: 2
    one_and_two:
      jobs:
        - build1
        - build2